name: test run

on:
  push:
  pull_request:

jobs:
  run-test:

    runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: pip install pytest

    - name: Install dependencies
      run: pip install pulp

    - name: Install dependencies
      run: pip install matplotlib

    - name: Test with pytest
      run: pytest

